import type { Metadata } from "next";
import { Bitter, Source_Sans_3 } from "next/font/google";
import "./styles/main.css";

const bitter = Bitter({
  subsets: ["latin"],
  variable: "--font-bitter",
});

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-source-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bitter.variable} ${sourceSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
